"""
core/server_manager.py
======================
Central controller for the Minecraft server subprocess lifecycle.

Responsibilities
----------------
â€¢ Download PaperMC jar if absent (via PaperMC v3 API (fill.papermc.io))
â€¢ Write eula.txt and a default server.properties
â€¢ Spawn / stop / kill the Java process
â€¢ Read STDOUT/STDERR in a background thread and broadcast to WebSocket clients
â€¢ Persist console output to a rotating log file
â€¢ Crash detection via a polling background task
â€¢ In-memory state machine: Offline â†’ Starting â†’ Running â†’ Stopping â†’ Crashed

Lifecycle safety
----------------
On FastAPI shutdown we GRACEFULLY STOP the Minecraft process (send 'stop',
wait up to STOP_TIMEOUT seconds, then terminate/kill).
Rationale: an abrupt shutdown risks world corruption. A graceful stop ensures
Minecraft flushes chunk data before the process exits, at the cost of a
slightly longer shutdown time.

Never allow two processes: a threading.Lock guards the start sequence.
"""

from __future__ import annotations

import asyncio
import logging
import os
import queue
import subprocess
import threading
import time
from datetime import datetime, timezone
from enum import Enum
from logging.handlers import RotatingFileHandler
from pathlib import Path
from typing import Any, Optional

import httpx

from core.config import get_settings, save_env_var, reload_settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
# Mojang Vanilla API
MOJANG_MANIFEST_URL = "https://piston-meta.mojang.com/mc/game/version_manifest_v2.json"
USER_AGENT = "NusatopiaManager/1.0 (github.com/Hasboy15S/Nusatopia)"
STOP_TIMEOUT = 30          # seconds to wait for graceful stop before force-kill
CRASH_POLL_INTERVAL = 3    # seconds between crash-detection polls
MAX_COMMAND_LEN = 256       # maximum bytes accepted from WebSocket command input
LOG_MAX_BYTES = 10 * 1024 * 1024   # 10 MB per rotating log slice
LOG_BACKUP_COUNT = 5


# ---------------------------------------------------------------------------
# Server status enum
# ---------------------------------------------------------------------------
class ServerStatus(str, Enum):
    OFFLINE = "Offline"
    STARTING = "Starting"
    RUNNING = "Running"
    STOPPING = "Stopping"
    CRASHED = "Crashed"


# ---------------------------------------------------------------------------
# WebSocket connection manager (console broadcast)
# ---------------------------------------------------------------------------
class ConnectionManager:
    """Tracks active WebSocket connections and fans out console lines."""

    def __init__(self) -> None:
        self._connections: set[Any] = set()
        self._lock = asyncio.Lock()

    async def connect(self, ws: Any) -> None:
        await ws.accept()
        async with self._lock:
            self._connections.add(ws)

    async def disconnect(self, ws: Any) -> None:
        async with self._lock:
            self._connections.discard(ws)

    async def broadcast(self, message: str) -> None:
        if not self._connections:
            return
        dead: set[Any] = set()
        async with self._lock:
            connections = set(self._connections)
        for ws in connections:
            try:
                await ws.send_text(message)
            except Exception:  # noqa: BLE001
                dead.add(ws)
        if dead:
            async with self._lock:
                self._connections -= dead


# ---------------------------------------------------------------------------
# Default server.properties
# ---------------------------------------------------------------------------
DEFAULT_PROPERTIES = """\
#Minecraft server properties
#Generated by MC Manager
server-port=25565
motd=A Minecraft Server (managed by MC Manager)
difficulty=normal
gamemode=survival
white-list=false
max-players=20
online-mode=false
level-name=world
view-distance=10
simulation-distance=10
enable-command-block=false
pvp=true
"""


# ---------------------------------------------------------------------------
# ServerManager
# ---------------------------------------------------------------------------
class ServerManager:
    """Singleton that owns the Minecraft subprocess and all related state."""

    def __init__(self) -> None:
        self._settings = get_settings()
        self._status: ServerStatus = ServerStatus.OFFLINE
        self._process: Optional[subprocess.Popen[bytes]] = None
        self._pid: Optional[int] = None
        self._start_time: Optional[datetime] = None
        self._exit_code: Optional[int] = None

        # Guards against concurrent start() calls
        self._start_lock = threading.Lock()

        # Thread-safe queue for console lines (stdout reader â†’ broadcast loop)
        self._output_queue: queue.Queue[str] = queue.Queue()

        # WebSocket fan-out manager (shared with main.py)
        self.console_manager = ConnectionManager()

        # Rotating file logger for console output
        self._console_logger = self._setup_console_logger()

        # asyncio event loop reference (set by main.py after startup)
        self._loop: Optional[asyncio.AbstractEventLoop] = None

        # Background task handles
        self._reader_thread: Optional[threading.Thread] = None
        self._crash_task: Optional[asyncio.Task[None]] = None
        self._broadcast_task: Optional[asyncio.Task[None]] = None

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _setup_console_logger(self) -> logging.Logger:
        log_path = self._settings.log_dir / "console.log"
        handler = RotatingFileHandler(
            log_path,
            maxBytes=LOG_MAX_BYTES,
            backupCount=LOG_BACKUP_COUNT,
            encoding="utf-8",
        )
        handler.setFormatter(logging.Formatter("%(asctime)s %(message)s"))
        con_logger = logging.getLogger("mc.console")
        con_logger.setLevel(logging.INFO)
        con_logger.addHandler(handler)
        con_logger.propagate = False
        return con_logger

    @property
    def status(self) -> ServerStatus:
        return self._status

    @property
    def pid(self) -> Optional[int]:
        return self._pid

    @property
    def uptime_seconds(self) -> Optional[float]:
        if self._start_time and self._status == ServerStatus.RUNNING:
            return (datetime.now(timezone.utc) - self._start_time).total_seconds()
        return None

    # ------------------------------------------------------------------
    # Setup: jar download, eula, properties
    # ------------------------------------------------------------------

    async def ensure_server_ready(self) -> None:
        """
        Run all pre-flight checks:
        1. Ensure server.jar exists (download from PaperMC if not).
        2. Write eula.txt.
        3. Write default server.properties if missing.
        """
        await self._ensure_jar()
        self._write_eula()
        self._write_default_properties()

    async def _ensure_jar(self) -> None:
        jar = self._settings.server_jar
        if jar.exists():
            logger.info("server.jar found at %s — skipping download.", jar)
            return

        logger.info("server.jar not found. Fetching Vanilla Mojang build...")
        dest = jar
        headers = {"User-Agent": USER_AGENT}

        async with httpx.AsyncClient(timeout=30.0, headers=headers) as client:
            try:
                mc_version = await self._resolve_mc_version(client)
                download_url = await self._resolve_download_url(client, mc_version)
                if download_url:
                    await self._download_jar_from_url(client, download_url, dest)
                    return
            except Exception as exc:
                logger.error("Mojang API resolution failed: %s", exc)
                raise RuntimeError(f"Gagal mendownload server: {exc}") from exc

    async def _resolve_mc_version(self, client: httpx.AsyncClient) -> str:
        """Resolve which MC version to use (pinned or latest release from Mojang)."""
        pinned = self._settings.mc_version
        if pinned:
            logger.info("Using pinned Minecraft version: %s", pinned)
            return pinned

        resp = await client.get(MOJANG_MANIFEST_URL)
        resp.raise_for_status()
        data = resp.json()
        latest = data.get("latest", {}).get("release")
        if not latest:
            raise ValueError("Could not determine latest release version from Mojang manifest.")
        return latest

    async def _resolve_download_url(self, client: httpx.AsyncClient, mc_version: str) -> Optional[str]:
        """
        Fetch Mojang manifest, find the specific version, get its metadata URL,
        then fetch that metadata to get the server jar download URL.
        """
        resp = await client.get(MOJANG_MANIFEST_URL)
        resp.raise_for_status()
        data = resp.json()
        versions = data.get("versions", [])
        
        version_meta_url = None
        for v in versions:
            if v.get("id") == mc_version:
                version_meta_url = v.get("url")
                break
                
        if not version_meta_url:
            raise ValueError(f"Versi {mc_version} tidak ditemukan di server resmi Mojang.")
            
        meta_resp = await client.get(version_meta_url)
        meta_resp.raise_for_status()
        meta_data = meta_resp.json()
        
        dl_url = meta_data.get("downloads", {}).get("server", {}).get("url")
        if not dl_url:
            raise ValueError(f"File server.jar tidak tersedia untuk versi {mc_version} di server Mojang.")
            
        return dl_url

    async def _download_jar_from_url(
        self,
        client: httpx.AsyncClient,
        download_url: str,
        dest: Path,
    ) -> None:
        logger.info("Downloading Vanilla server jar from: %s", download_url)
        dest.parent.mkdir(parents=True, exist_ok=True)
        tmp = dest.with_suffix(".tmp")

        # If a fully downloaded temp file already exists (>20MB), promote it directly
        if tmp.exists() and tmp.stat().st_size > 20 * 1024 * 1024:
            logger.info("Found completed temp download (%d bytes), promoting to server.jar...", tmp.stat().st_size)
            tmp.rename(dest)
            return

        max_attempts = 3
        for attempt in range(1, max_attempts + 1):
            downloaded = 0
            try:
                async with client.stream("GET", download_url) as resp:
                    resp.raise_for_status()
                    total = int(resp.headers.get("content-length", 0))
                    with open(tmp, "wb") as f:
                        async for chunk in resp.aiter_bytes(chunk_size=65536):
                            f.write(chunk)
                            downloaded += len(chunk)
                            if total:
                                logger.debug("Download progress: %.1f%%", downloaded / total * 100)

                tmp.rename(dest)
                logger.info("Vanilla server jar saved to %s (%d bytes)", dest, downloaded)
                return
            except Exception as exc:
                logger.warning("Download attempt %d/%d failed (%s). Retrying...", attempt, max_attempts, exc)
                if tmp.exists():
                    tmp.unlink(missing_ok=True)
                if attempt == max_attempts:
                    raise RuntimeError(f"Failed to download server jar after {max_attempts} attempts: {exc}") from exc
                await asyncio.sleep(2)

    def _write_eula(self) -> None:
        eula = self._settings.eula_file
        eula.write_text("eula=true\n", encoding="utf-8")
        logger.info("eula.txt written (eula=true).")

    def _write_default_properties(self) -> None:
        props = self._settings.properties_file
        if not props.exists():
            props.write_text(DEFAULT_PROPERTIES, encoding="utf-8")
            logger.info("Default server.properties written.")
        else:
            logger.info("server.properties already exists â€” not overwriting.")

    # ------------------------------------------------------------------
    # server.properties read / write
    # ------------------------------------------------------------------

    def read_properties(self) -> dict[str, str]:
        """Parse server.properties into a dict (comments stripped)."""
        props: dict[str, str] = {}
        path = self._settings.properties_file
        if not path.exists():
            return props
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                props[key.strip()] = value.strip()
        return props

    def write_properties(self, updates: dict[str, str]) -> None:
        """
        Merge `updates` into the current server.properties, preserving
        comment lines and the order of existing keys.
        """
        path = self._settings.properties_file
        lines: list[str] = []
        existing_keys: set[str] = set()

        if path.exists():
            for line in path.read_text(encoding="utf-8").splitlines():
                stripped = line.strip()
                if stripped.startswith("#") or not stripped:
                    lines.append(line)
                    continue
                if "=" in stripped:
                    key, _, _ = stripped.partition("=")
                    key = key.strip()
                    existing_keys.add(key)
                    if key in updates:
                        lines.append(f"{key}={updates[key]}")
                    else:
                        lines.append(line)
                else:
                    lines.append(line)

        # Append keys that didn't exist yet
        for key, value in updates.items():
            if key not in existing_keys:
                lines.append(f"{key}={value}")

        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        logger.info("server.properties updated with keys: %s", list(updates.keys()))

    # ------------------------------------------------------------------
    # Version management
    # ------------------------------------------------------------------

    async def get_available_versions(self) -> dict:
        """
        Fetch all available Minecraft release versions supported by Mojang.
        Returns a dict with 'current' (active version) and 'versions' (list of version strings).
        """
        headers = {"User-Agent": USER_AGENT}
        current = self._settings.mc_version or "(latest)"
        versions: list[str] = []

        try:
            async with httpx.AsyncClient(timeout=15.0, headers=headers) as client:
                resp = await client.get(MOJANG_MANIFEST_URL)
                resp.raise_for_status()
                data = resp.json()
                
                # Fetch all versions, both releases and snapshots (in case user wants 26.3 or custom)
                for v in data.get("versions", []):
                    vid = v.get("id")
                    if vid:
                        versions.append(vid)

            # Keep top 200 to avoid massive payloads
            versions = versions[:200]
        except Exception as exc:
            logger.warning("Failed to fetch Mojang versions: %s", exc)
            versions = ["1.21.4", "1.21.1", "1.20.6", "1.20.4", "1.19.4"]

        return {"current": current, "versions": versions}

    @staticmethod
    def _version_sort_key(version: str) -> tuple:
        """Turn '1.21.4' into (1, 21, 4) for numeric sorting."""
        parts = []
        for p in version.split("."):
            try:
                parts.append(int(p))
            except ValueError:
                parts.append(0)
        return tuple(parts)

    async def change_version(self, new_version: str) -> dict:
        """
        Switch the Minecraft server to a different version.
        Server MUST be offline. Steps:
        1. Validate server is offline.
        2. Delete existing server.jar.
        3. Persist MC_VERSION to .env.
        4. Reload settings.
        5. Download the new jar.
        """
        if self._status not in (ServerStatus.OFFLINE, ServerStatus.CRASHED):
            raise RuntimeError(
                f"Server must be offline to change version (current: {self._status.value})."
            )

        new_version = new_version.strip()
        if not new_version:
            raise ValueError("Version string must not be empty.")

        logger.info("Changing Minecraft version to %s ...", new_version)

        # 1. Remove existing server.jar so _ensure_jar will re-download
        jar = self._settings.server_jar
        if jar.exists():
            jar.unlink()
            logger.info("Removed old server.jar at %s", jar)

        # 2. Persist the new version to .env and reload settings
        save_env_var("MC_VERSION", new_version)
        self._settings = reload_settings()

        # 3. Download the new jar
        await self._ensure_jar()

        return {
            "message": f"Version changed to {new_version}. Server jar downloaded.",
            "version": new_version,
        }

    # ------------------------------------------------------------------
    # Process lifecycle
    # ------------------------------------------------------------------

    async def start(self) -> None:
        """
        Start the Minecraft server.
        Raises RuntimeError if already running or starting.
        """
        if self._status in (ServerStatus.RUNNING, ServerStatus.STARTING):
            raise RuntimeError(f"Server is already {self._status.value}.")

        if not self._start_lock.acquire(blocking=False):
            raise RuntimeError("Start is already in progress.")

        try:
            await self.ensure_server_ready()
            self._status = ServerStatus.STARTING
            self._exit_code = None
            self._launch_process()
        except Exception:
            self._status = ServerStatus.OFFLINE
            self._start_lock.release()
            raise
        else:
            self._start_lock.release()

    def _launch_process(self) -> None:
        settings = self._settings
        cmd = [
            settings.java_executable,
            f"-Xmx{settings.mc_ram_max}",
            f"-Xms{settings.mc_ram_min}",
            "-jar",
            str(settings.server_jar.name),
            "nogui",
        ]
        logger.info("Launching: %s", " ".join(cmd))

        self._process = subprocess.Popen(
            cmd,
            cwd=str(settings.mc_server_dir),
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,   # merge stderr into stdout
            bufsize=1,
        )
        self._pid = self._process.pid
        self._start_time = datetime.now(timezone.utc)
        self._status = ServerStatus.RUNNING

        # Start background reader thread
        self._reader_thread = threading.Thread(
            target=self._stdout_reader,
            daemon=True,
            name="mc-stdout-reader",
        )
        self._reader_thread.start()

        # Schedule async tasks on the running event loop
        if self._loop:
            self._crash_task = self._loop.create_task(self._crash_watcher())
            self._broadcast_task = self._loop.create_task(self._broadcast_loop())

        logger.info("Minecraft server started (PID=%d).", self._pid)

    def _stdout_reader(self) -> None:
        """Thread: reads lines from the Java process and enqueues them."""
        assert self._process and self._process.stdout
        try:
            for raw_line in iter(self._process.stdout.readline, b""):
                line = raw_line.decode("utf-8", errors="replace").rstrip()
                self._output_queue.put(line)
                self._console_logger.info(line)
        except Exception as exc:  # noqa: BLE001
            logger.error("STDOUT reader error: %s", exc)
        finally:
            logger.debug("STDOUT reader thread exiting.")

    async def _broadcast_loop(self) -> None:
        """Async task: drain the output queue and fan out to WebSocket clients."""
        loop = asyncio.get_running_loop()
        while self._status != ServerStatus.OFFLINE:
            try:
                line: str = await loop.run_in_executor(
                    None, lambda: self._output_queue.get(timeout=0.5)
                )
                await self.console_manager.broadcast(line)
            except queue.Empty:
                continue
            except asyncio.CancelledError:
                break
            except Exception as exc:  # noqa: BLE001
                logger.error("Broadcast loop error: %s", exc)

    async def _crash_watcher(self) -> None:
        """
        Async task: periodically checks if the process is still alive.
        If the process exits unexpectedly while status == RUNNING, flip to CRASHED.
        """
        while True:
            await asyncio.sleep(CRASH_POLL_INTERVAL)
            if self._process is None:
                break
            ret = self._process.poll()
            if ret is not None:
                self._exit_code = ret
                if self._status == ServerStatus.RUNNING:
                    logger.error(
                        "Minecraft process (PID=%d) exited unexpectedly with code %d. "
                        "Status set to Crashed.",
                        self._pid,
                        ret,
                    )
                    self._status = ServerStatus.CRASHED
                    await self.console_manager.broadcast(
                        f"[MC Manager] Server CRASHED (exit code {ret})."
                    )
                break
            # Also promote Starting â†’ Running when we see the done message
            if self._status == ServerStatus.STARTING:
                # Minecraft prints "Done" when ready
                pass  # handled implicitly; console output is already streamed

    async def stop(self) -> None:
        """
        Gracefully stop the server.
        1. Send 'stop' to STDIN.
        2. Wait up to STOP_TIMEOUT seconds for the process to exit.
        3. If it doesn't exit, terminate() then kill().
        """
        if self._status in (ServerStatus.OFFLINE, ServerStatus.CRASHED):
            raise RuntimeError(f"Server is already {self._status.value}.")
        if self._status == ServerStatus.STOPPING:
            raise RuntimeError("Server is already stopping.")

        self._status = ServerStatus.STOPPING
        logger.info("Sending 'stop' command to Minecraft serverâ€¦")

        try:
            await self._send_command_raw("stop")
        except Exception as exc:
            logger.warning("Could not write 'stop' to STDIN: %s", exc)

        # Wait for process to exit
        loop = asyncio.get_running_loop()
        deadline = time.monotonic() + STOP_TIMEOUT

        while time.monotonic() < deadline:
            ret = self._process.poll() if self._process else None
            if ret is not None:
                self._exit_code = ret
                break
            await asyncio.sleep(0.5)
        else:
            logger.warning(
                "Server did not stop within %ds â€” escalating to terminate/kill.", STOP_TIMEOUT
            )
            self._escalate_kill()

        self._cleanup()

    def _escalate_kill(self) -> None:
        if self._process is None:
            return
        try:
            self._process.terminate()
            time.sleep(2)
            if self._process.poll() is None:
                self._process.kill()
        except OSError as exc:
            logger.error("Error killing process: %s", exc)

    def _cleanup(self) -> None:
        self._status = ServerStatus.OFFLINE
        self._pid = None
        self._start_time = None
        self._process = None
        logger.info("Server process cleaned up.")

    # ------------------------------------------------------------------
    # Console command dispatch
    # ------------------------------------------------------------------

    async def send_command(self, command: str) -> None:
        """
        Validate and write a command to the Minecraft server's STDIN.
        Raises ValueError for invalid input, RuntimeError if not running.
        """
        command = command.strip()
        if not command:
            raise ValueError("Command must not be empty.")
        if len(command) > MAX_COMMAND_LEN:
            raise ValueError(
                f"Command exceeds maximum length of {MAX_COMMAND_LEN} characters."
            )
        if self._status != ServerStatus.RUNNING:
            raise RuntimeError("Server is not running.")
        await self._send_command_raw(command)

    async def _send_command_raw(self, command: str) -> None:
        """Write a raw command line to the process STDIN (no validation)."""
        if self._process is None or self._process.stdin is None:
            raise RuntimeError("No active server process.")
        loop = asyncio.get_running_loop()
        await loop.run_in_executor(
            None,
            lambda: (
                self._process.stdin.write(f"{command}\n".encode()),  # type: ignore[union-attr]
                self._process.stdin.flush(),
            ),
        )

    # ------------------------------------------------------------------
    # Startup integration
    # ------------------------------------------------------------------

    def set_event_loop(self, loop: asyncio.AbstractEventLoop) -> None:
        """Called by main.py once the uvicorn event loop is known."""
        self._loop = loop

    async def graceful_shutdown(self) -> None:
        """Called by FastAPI lifespan on app shutdown to stop Minecraft first."""
        if self._status in (ServerStatus.RUNNING, ServerStatus.STARTING, ServerStatus.STOPPING):
            logger.info("App shutting down â€” gracefully stopping Minecraft serverâ€¦")
            try:
                await self.stop()
            except Exception as exc:  # noqa: BLE001
                logger.error("Error during graceful shutdown: %s", exc)
        # Cancel background tasks
        for task in (self._crash_task, self._broadcast_task):
            if task and not task.done():
                task.cancel()


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------
server_manager = ServerManager()



