"""
core/server_manager.py
======================
Central controller for the Minecraft server subprocess lifecycle.

Responsibilities
----------------
â€¢ Download PaperMC jar if absent (via PaperMC v3 API (fill.papermc.io))
â€¢ Write eula.txt and a default server.properties
â€¢ Spawn / stop / kill the Java process
â€¢ Read STDOUT/STDERR in a background thread and broadcast to WebSocket clients
â€¢ Persist console output to a rotating log file
â€¢ Crash detection via a polling background task
â€¢ In-memory state machine: Offline â†’ Starting â†’ Running â†’ Stopping â†’ Crashed

Lifecycle safety
----------------
On FastAPI shutdown we GRACEFULLY STOP the Minecraft process (send 'stop',
wait up to STOP_TIMEOUT seconds, then terminate/kill).
Rationale: an abrupt shutdown risks world corruption. A graceful stop ensures
Minecraft flushes chunk data before the process exits, at the cost of a
slightly longer shutdown time.

Never allow two processes: a threading.Lock guards the start sequence.
"""

from __future__ import annotations

import asyncio
import logging
import os
import queue
import subprocess
import threading
import time
from datetime import datetime, timezone
from enum import Enum
from logging.handlers import RotatingFileHandler
from pathlib import Path
from typing import Any, Optional

import httpx

from core.config import get_settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
# PaperMC migrated from api.papermc.io/v2 (sunset) to fill.papermc.io/v3
PAPERMC_API_BASE   = "https://fill.papermc.io/v3/projects/paper"
PAPERMC_USER_AGENT = "NusatopiaManager/1.0 (github.com/Hasboy15S/Nusatopia)"
FALLBACK_JAR_URL   = "https://fill-data.papermc.io/v1/objects/05209ac5a423bf98136dd775a87d4324955d2c865f887b20edd6b43a59cb36c4/paper-1.21.4-1.jar"
STOP_TIMEOUT = 30          # seconds to wait for graceful stop before force-kill
CRASH_POLL_INTERVAL = 3    # seconds between crash-detection polls
MAX_COMMAND_LEN = 256       # maximum bytes accepted from WebSocket command input
LOG_MAX_BYTES = 10 * 1024 * 1024   # 10 MB per rotating log slice
LOG_BACKUP_COUNT = 5


# ---------------------------------------------------------------------------
# Server status enum
# ---------------------------------------------------------------------------
class ServerStatus(str, Enum):
    OFFLINE = "Offline"
    STARTING = "Starting"
    RUNNING = "Running"
    STOPPING = "Stopping"
    CRASHED = "Crashed"


# ---------------------------------------------------------------------------
# WebSocket connection manager (console broadcast)
# ---------------------------------------------------------------------------
class ConnectionManager:
    """Tracks active WebSocket connections and fans out console lines."""

    def __init__(self) -> None:
        self._connections: set[Any] = set()
        self._lock = asyncio.Lock()

    async def connect(self, ws: Any) -> None:
        await ws.accept()
        async with self._lock:
            self._connections.add(ws)

    async def disconnect(self, ws: Any) -> None:
        async with self._lock:
            self._connections.discard(ws)

    async def broadcast(self, message: str) -> None:
        if not self._connections:
            return
        dead: set[Any] = set()
        async with self._lock:
            connections = set(self._connections)
        for ws in connections:
            try:
                await ws.send_text(message)
            except Exception:  # noqa: BLE001
                dead.add(ws)
        if dead:
            async with self._lock:
                self._connections -= dead


# ---------------------------------------------------------------------------
# Default server.properties
# ---------------------------------------------------------------------------
DEFAULT_PROPERTIES = """\
#Minecraft server properties
#Generated by MC Manager
server-port=25565
motd=A Minecraft Server (managed by MC Manager)
difficulty=normal
gamemode=survival
white-list=false
max-players=20
online-mode=true
level-name=world
view-distance=10
simulation-distance=10
enable-command-block=false
pvp=true
"""


# ---------------------------------------------------------------------------
# ServerManager
# ---------------------------------------------------------------------------
class ServerManager:
    """Singleton that owns the Minecraft subprocess and all related state."""

    def __init__(self) -> None:
        self._settings = get_settings()
        self._status: ServerStatus = ServerStatus.OFFLINE
        self._process: Optional[subprocess.Popen[bytes]] = None
        self._pid: Optional[int] = None
        self._start_time: Optional[datetime] = None
        self._exit_code: Optional[int] = None

        # Guards against concurrent start() calls
        self._start_lock = threading.Lock()

        # Thread-safe queue for console lines (stdout reader â†’ broadcast loop)
        self._output_queue: queue.Queue[str] = queue.Queue()

        # WebSocket fan-out manager (shared with main.py)
        self.console_manager = ConnectionManager()

        # Rotating file logger for console output
        self._console_logger = self._setup_console_logger()

        # asyncio event loop reference (set by main.py after startup)
        self._loop: Optional[asyncio.AbstractEventLoop] = None

        # Background task handles
        self._reader_thread: Optional[threading.Thread] = None
        self._crash_task: Optional[asyncio.Task[None]] = None
        self._broadcast_task: Optional[asyncio.Task[None]] = None

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _setup_console_logger(self) -> logging.Logger:
        log_path = self._settings.log_dir / "console.log"
        handler = RotatingFileHandler(
            log_path,
            maxBytes=LOG_MAX_BYTES,
            backupCount=LOG_BACKUP_COUNT,
            encoding="utf-8",
        )
        handler.setFormatter(logging.Formatter("%(asctime)s %(message)s"))
        con_logger = logging.getLogger("mc.console")
        con_logger.setLevel(logging.INFO)
        con_logger.addHandler(handler)
        con_logger.propagate = False
        return con_logger

    @property
    def status(self) -> ServerStatus:
        return self._status

    @property
    def pid(self) -> Optional[int]:
        return self._pid

    @property
    def uptime_seconds(self) -> Optional[float]:
        if self._start_time and self._status == ServerStatus.RUNNING:
            return (datetime.now(timezone.utc) - self._start_time).total_seconds()
        return None

    # ------------------------------------------------------------------
    # Setup: jar download, eula, properties
    # ------------------------------------------------------------------

    async def ensure_server_ready(self) -> None:
        """
        Run all pre-flight checks:
        1. Ensure server.jar exists (download from PaperMC if not).
        2. Write eula.txt.
        3. Write default server.properties if missing.
        """
        await self._ensure_jar()
        self._write_eula()
        self._write_default_properties()

    async def _ensure_jar(self) -> None:
        jar = self._settings.server_jar
        if jar.exists():
            logger.info("server.jar found at %s — skipping download.", jar)
            return

        logger.info("server.jar not found. Fetching PaperMC build...")
        dest = jar
        headers = {"User-Agent": PAPERMC_USER_AGENT}

        # Try dynamic resolution via PaperMC Fill v3 API
        try:
            async with httpx.AsyncClient(timeout=20.0, headers=headers) as client:
                mc_version = await self._resolve_mc_version(client)
                download_url = await self._resolve_download_url(client, mc_version)
                if download_url:
                    await self._download_jar_from_url(client, download_url, dest)
                    return
        except Exception as exc:
            logger.warning("PaperMC API resolution failed (%s). Falling back to direct static download.", exc)

        # Fallback to direct static download if API resolution fails or returns no URL
        logger.info("Downloading PaperMC 1.21.4 jar via fallback direct URL...")
        async with httpx.AsyncClient(timeout=60.0, headers=headers, follow_redirects=True) as client:
            await self._download_jar_from_url(client, FALLBACK_JAR_URL, dest)

    async def _resolve_mc_version(self, client: httpx.AsyncClient) -> str:
        """Resolve which MC version to use (pinned or latest from Fill v3 API)."""
        pinned = self._settings.mc_version
        if pinned:
            logger.info("Using pinned Minecraft version: %s", pinned)
            return pinned

        try:
            resp = await client.get(PAPERMC_API_BASE)
            resp.raise_for_status()
            raw = resp.json().get("versions", {})
            if isinstance(raw, dict):
                # Check for "1.21" family first
                if "1.21" in raw and raw["1.21"]:
                    for v in raw["1.21"]:
                        if v == "1.21.4":
                            return "1.21.4"
                    return raw["1.21"][0]
                for key, v_list in raw.items():
                    if isinstance(v_list, list) and v_list:
                        return v_list[0]
            elif isinstance(raw, list) and raw:
                return str(raw[-1])
        except Exception as e:
            logger.warning("Failed to parse MC versions from API: %s", e)

        return "1.21.4"

    async def _resolve_download_url(self, client: httpx.AsyncClient, mc_version: str) -> Optional[str]:
        """
        Fill v3: GET /v3/projects/paper/versions/{version}/builds
        Returns list of build objects; builds[0] is the latest build.
        """
        url = f"{PAPERMC_API_BASE}/versions/{mc_version}/builds"
        resp = await client.get(url)
        resp.raise_for_status()
        data = resp.json()
        builds = data if isinstance(data, list) else data.get("builds", [])
        if not builds:
            return None

        chosen = builds[0]
        downloads = chosen.get("downloads", {})

        # Look for any download entry with a valid 'url'
        for dl_key, dl_val in downloads.items():
            if isinstance(dl_val, dict) and "url" in dl_val:
                return dl_val["url"]

        return None

    async def _download_jar_from_url(
        self,
        client: httpx.AsyncClient,
        download_url: str,
        dest: Path,
    ) -> None:
        logger.info("Downloading PaperMC jar from: %s", download_url)
        dest.parent.mkdir(parents=True, exist_ok=True)
        tmp = dest.with_suffix(".tmp")

        # If a fully downloaded temp file already exists (>50MB), promote it directly
        if tmp.exists() and tmp.stat().st_size > 50 * 1024 * 1024:
            logger.info("Found completed temp download (%d bytes), promoting to server.jar...", tmp.stat().st_size)
            tmp.rename(dest)
            return

        max_attempts = 3
        for attempt in range(1, max_attempts + 1):
            downloaded = 0
            try:
                async with client.stream("GET", download_url) as resp:
                    resp.raise_for_status()
                    total = int(resp.headers.get("content-length", 0))
                    with open(tmp, "wb") as f:
                        async for chunk in resp.aiter_bytes(chunk_size=65536):
                            f.write(chunk)
                            downloaded += len(chunk)
                            if total:
                                logger.debug("Download progress: %.1f%%", downloaded / total * 100)

                tmp.rename(dest)
                logger.info("PaperMC jar saved to %s (%d bytes)", dest, downloaded)
                return
            except Exception as exc:
                logger.warning("Download attempt %d/%d failed (%s). Retrying...", attempt, max_attempts, exc)
                if tmp.exists():
                    tmp.unlink(missing_ok=True)
                if attempt == max_attempts:
                    raise RuntimeError(f"Failed to download PaperMC jar after {max_attempts} attempts: {exc}") from exc
                await asyncio.sleep(2)

    def _write_eula(self) -> None:
        eula = self._settings.eula_file
        eula.write_text("eula=true\n", encoding="utf-8")
        logger.info("eula.txt written (eula=true).")

    def _write_default_properties(self) -> None:
        props = self._settings.properties_file
        if not props.exists():
            props.write_text(DEFAULT_PROPERTIES, encoding="utf-8")
            logger.info("Default server.properties written.")
        else:
            logger.info("server.properties already exists â€” not overwriting.")

    # ------------------------------------------------------------------
    # server.properties read / write
    # ------------------------------------------------------------------

    def read_properties(self) -> dict[str, str]:
        """Parse server.properties into a dict (comments stripped)."""
        props: dict[str, str] = {}
        path = self._settings.properties_file
        if not path.exists():
            return props
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                props[key.strip()] = value.strip()
        return props

    def write_properties(self, updates: dict[str, str]) -> None:
        """
        Merge `updates` into the current server.properties, preserving
        comment lines and the order of existing keys.
        """
        path = self._settings.properties_file
        lines: list[str] = []
        existing_keys: set[str] = set()

        if path.exists():
            for line in path.read_text(encoding="utf-8").splitlines():
                stripped = line.strip()
                if stripped.startswith("#") or not stripped:
                    lines.append(line)
                    continue
                if "=" in stripped:
                    key, _, _ = stripped.partition("=")
                    key = key.strip()
                    existing_keys.add(key)
                    if key in updates:
                        lines.append(f"{key}={updates[key]}")
                    else:
                        lines.append(line)
                else:
                    lines.append(line)

        # Append keys that didn't exist yet
        for key, value in updates.items():
            if key not in existing_keys:
                lines.append(f"{key}={value}")

        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        logger.info("server.properties updated with keys: %s", list(updates.keys()))

    # ------------------------------------------------------------------
    # Process lifecycle
    # ------------------------------------------------------------------

    async def start(self) -> None:
        """
        Start the Minecraft server.
        Raises RuntimeError if already running or starting.
        """
        if self._status in (ServerStatus.RUNNING, ServerStatus.STARTING):
            raise RuntimeError(f"Server is already {self._status.value}.")

        if not self._start_lock.acquire(blocking=False):
            raise RuntimeError("Start is already in progress.")

        try:
            await self.ensure_server_ready()
            self._status = ServerStatus.STARTING
            self._exit_code = None
            self._launch_process()
        except Exception:
            self._status = ServerStatus.OFFLINE
            self._start_lock.release()
            raise
        else:
            self._start_lock.release()

    def _launch_process(self) -> None:
        settings = self._settings
        cmd = [
            settings.java_executable,
            f"-Xmx{settings.mc_ram_max}",
            f"-Xms{settings.mc_ram_min}",
            "-jar",
            str(settings.server_jar.name),
            "nogui",
        ]
        logger.info("Launching: %s", " ".join(cmd))

        self._process = subprocess.Popen(
            cmd,
            cwd=str(settings.mc_server_dir),
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,   # merge stderr into stdout
            bufsize=1,
        )
        self._pid = self._process.pid
        self._start_time = datetime.now(timezone.utc)
        self._status = ServerStatus.RUNNING

        # Start background reader thread
        self._reader_thread = threading.Thread(
            target=self._stdout_reader,
            daemon=True,
            name="mc-stdout-reader",
        )
        self._reader_thread.start()

        # Schedule async tasks on the running event loop
        if self._loop:
            self._crash_task = self._loop.create_task(self._crash_watcher())
            self._broadcast_task = self._loop.create_task(self._broadcast_loop())

        logger.info("Minecraft server started (PID=%d).", self._pid)

    def _stdout_reader(self) -> None:
        """Thread: reads lines from the Java process and enqueues them."""
        assert self._process and self._process.stdout
        try:
            for raw_line in iter(self._process.stdout.readline, b""):
                line = raw_line.decode("utf-8", errors="replace").rstrip()
                self._output_queue.put(line)
                self._console_logger.info(line)
        except Exception as exc:  # noqa: BLE001
            logger.error("STDOUT reader error: %s", exc)
        finally:
            logger.debug("STDOUT reader thread exiting.")

    async def _broadcast_loop(self) -> None:
        """Async task: drain the output queue and fan out to WebSocket clients."""
        loop = asyncio.get_running_loop()
        while self._status != ServerStatus.OFFLINE:
            try:
                line: str = await loop.run_in_executor(
                    None, lambda: self._output_queue.get(timeout=0.5)
                )
                await self.console_manager.broadcast(line)
            except queue.Empty:
                continue
            except asyncio.CancelledError:
                break
            except Exception as exc:  # noqa: BLE001
                logger.error("Broadcast loop error: %s", exc)

    async def _crash_watcher(self) -> None:
        """
        Async task: periodically checks if the process is still alive.
        If the process exits unexpectedly while status == RUNNING, flip to CRASHED.
        """
        while True:
            await asyncio.sleep(CRASH_POLL_INTERVAL)
            if self._process is None:
                break
            ret = self._process.poll()
            if ret is not None:
                self._exit_code = ret
                if self._status == ServerStatus.RUNNING:
                    logger.error(
                        "Minecraft process (PID=%d) exited unexpectedly with code %d. "
                        "Status set to Crashed.",
                        self._pid,
                        ret,
                    )
                    self._status = ServerStatus.CRASHED
                    await self.console_manager.broadcast(
                        f"[MC Manager] Server CRASHED (exit code {ret})."
                    )
                break
            # Also promote Starting â†’ Running when we see the done message
            if self._status == ServerStatus.STARTING:
                # Minecraft prints "Done" when ready
                pass  # handled implicitly; console output is already streamed

    async def stop(self) -> None:
        """
        Gracefully stop the server.
        1. Send 'stop' to STDIN.
        2. Wait up to STOP_TIMEOUT seconds for the process to exit.
        3. If it doesn't exit, terminate() then kill().
        """
        if self._status in (ServerStatus.OFFLINE, ServerStatus.CRASHED):
            raise RuntimeError(f"Server is already {self._status.value}.")
        if self._status == ServerStatus.STOPPING:
            raise RuntimeError("Server is already stopping.")

        self._status = ServerStatus.STOPPING
        logger.info("Sending 'stop' command to Minecraft serverâ€¦")

        try:
            await self._send_command_raw("stop")
        except Exception as exc:
            logger.warning("Could not write 'stop' to STDIN: %s", exc)

        # Wait for process to exit
        loop = asyncio.get_running_loop()
        deadline = time.monotonic() + STOP_TIMEOUT

        while time.monotonic() < deadline:
            ret = self._process.poll() if self._process else None
            if ret is not None:
                self._exit_code = ret
                break
            await asyncio.sleep(0.5)
        else:
            logger.warning(
                "Server did not stop within %ds â€” escalating to terminate/kill.", STOP_TIMEOUT
            )
            self._escalate_kill()

        self._cleanup()

    def _escalate_kill(self) -> None:
        if self._process is None:
            return
        try:
            self._process.terminate()
            time.sleep(2)
            if self._process.poll() is None:
                self._process.kill()
        except OSError as exc:
            logger.error("Error killing process: %s", exc)

    def _cleanup(self) -> None:
        self._status = ServerStatus.OFFLINE
        self._pid = None
        self._start_time = None
        self._process = None
        logger.info("Server process cleaned up.")

    # ------------------------------------------------------------------
    # Console command dispatch
    # ------------------------------------------------------------------

    async def send_command(self, command: str) -> None:
        """
        Validate and write a command to the Minecraft server's STDIN.
        Raises ValueError for invalid input, RuntimeError if not running.
        """
        command = command.strip()
        if not command:
            raise ValueError("Command must not be empty.")
        if len(command) > MAX_COMMAND_LEN:
            raise ValueError(
                f"Command exceeds maximum length of {MAX_COMMAND_LEN} characters."
            )
        if self._status != ServerStatus.RUNNING:
            raise RuntimeError("Server is not running.")
        await self._send_command_raw(command)

    async def _send_command_raw(self, command: str) -> None:
        """Write a raw command line to the process STDIN (no validation)."""
        if self._process is None or self._process.stdin is None:
            raise RuntimeError("No active server process.")
        loop = asyncio.get_running_loop()
        await loop.run_in_executor(
            None,
            lambda: (
                self._process.stdin.write(f"{command}\n".encode()),  # type: ignore[union-attr]
                self._process.stdin.flush(),
            ),
        )

    # ------------------------------------------------------------------
    # Startup integration
    # ------------------------------------------------------------------

    def set_event_loop(self, loop: asyncio.AbstractEventLoop) -> None:
        """Called by main.py once the uvicorn event loop is known."""
        self._loop = loop

    async def graceful_shutdown(self) -> None:
        """Called by FastAPI lifespan on app shutdown to stop Minecraft first."""
        if self._status in (ServerStatus.RUNNING, ServerStatus.STARTING, ServerStatus.STOPPING):
            logger.info("App shutting down â€” gracefully stopping Minecraft serverâ€¦")
            try:
                await self.stop()
            except Exception as exc:  # noqa: BLE001
                logger.error("Error during graceful shutdown: %s", exc)
        # Cancel background tasks
        for task in (self._crash_task, self._broadcast_task):
            if task and not task.done():
                task.cancel()


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------
server_manager = ServerManager()



